CREATE TABLE REGIONS(
                REGION_ID NUMBER,
                REGION_NAME VARCHAR2(25),
                CONSTRAINT pk_region_id PRIMARY KEY (REGION_ID));
            
CREATE TABLE COUNTRIES(
                COUNTRY_ID CHAR(2),
                COUNTRY_NAME VARCHAR2(40),
                REGION_ID NUMBER,
                CONSTRAINT COUNTR_REG_FK FOREIGN KEY (REGION_ID)
                REFERENCES REGIONS(REGION_ID),
                CONSTRAINT pk_COUNTRY_ID PRIMARY KEY (COUNTRY_ID));
          
                
CREATE TABLE LOCATIONS(     
                LOCATION_ID NUMBER(4),
                STREET_ADDRESS VARCHAR2(40),
                POSTAL_CODE VARCHAR2(12),
                CITY VARCHAR2(30),
                STATE_PROVINCE VARCHAR2(25),
                COUNTRY_ID CHAR(2),
                CONSTRAINT pk_LOCATION_ID PRIMARY KEY (LOCATION_ID),
                CONSTRAINT LOC_C_ID_FK FOREIGN KEY (COUNTRY_ID)
                REFERENCES COUNTRIES(COUNTRY_ID));


CREATE TABLE DEPARTMENTS(
                DEPARTMENT_ID NUMBER(4),
                DEPARTMENT_NAME VARCHAR2(30),
                MANAGER_ID NUMBER(6),
                LOCATION_ID NUMBER(4),
                CONSTRAINT pk_DEPARTMENT_ID PRIMARY KEY (DEPARTMENT_ID),
                CONSTRAINT DEPT_LOC_FK FOREIGN KEY (LOCATION_ID)
                REFERENCES LOCATIONS(LOCATION_ID));
--                CONSTRAINT DEPT_MGR_FK FOREIGN KEY (MANAGER_ID)
--                REFERENCES EMPLOYEES(MANAGER_ID));


CREATE TABLE JOB_HISTORY(
                EMPLOYEE_ID NUMBER(6),
                START_DATE DATE,
                END_DATE DATE,
                JOB_ID VARCHAR2(10),
                DEPARTMENT_ID NUMBER(4),
                CONSTRAINT pk_EMPLOYEE_ID_pk_START_DATE PRIMARY KEY (EMPLOYEE_ID, START_DATE),
                CONSTRAINT JHIST_JOB_FK FOREIGN KEY (JOB_ID)
                REFERENCES JOBS(JOB_ID));
--                CONSTRAINT JHIST_DEPT_FK FOREIGN KEY (DEPARTMENT_ID)
--                REFERENCES DEPARTMENTS(DEPARTMENT_ID));


CREATE TABLE JOBS(
                JOB_ID VARCHAR2(10),
                JOB_TITLE VARCHAR2(35),
                MIN_SALARY NUMBER(6),
                MAX_SALARY NUMBER(6),
                CONSTRAINT pk_JOB_ID PRIMARY KEY (JOB_ID));


CREATE TABLE EMPLOYEES(
                EMPLOYEE_ID NUMBER(6),
                FIRST_NAME VARCHAR2(20),
                LAST_NAME VARCHAR2(25),
                EMAIL VARCHAR2(25),
                PHONE_NUMBER VARCHAR2(20),
                HIRE_DATE DATE,
                JOB_ID VARCHAR2(10),
                SALARY NUMBER(8, 2),
                COMMISSION_PCT NUMBER(2, 2),
                MANAGER_ID NUMBER(6),
                DEPARTMENT_ID NUMBER(4),
                CONSTRAINT pk_EMPLOYEE_ID PRIMARY KEY (EMPLOYEE_ID),
--                CONSTRAINT EMP_MANAGER_FK FOREIGN KEY (MANAGER_ID)
--                REFERENCES EMPLOYEES(MANAGER_ID),
                CONSTRAINT EMP_DEPT_FK FOREIGN KEY (DEPARTMENT_ID)
                REFERENCES DEPARTMENTS(DEPARTMENT_ID),
                CONSTRAINT EMP_JOB_FK FOREIGN KEY (JOB_ID)
                REFERENCES JOBS(JOB_ID));


ALTER TABLE EMPLOYEES ADD CONSTRAINT EMP_MANAGER_FK FOREIGN KEY (MANAGER_ID)
REFERENCES EMPLOYEES(EMPLOYEE_ID);






